config/routes.rb
Rails.application.routes.draw do
  post 'records/save_file' => 'records#create'
  resources :exercises

  resources :trainings

  root 'trainings#index'

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  mount_uploader :audio, AudioUploader
end

app/models/training.rb
class Training < ActiveRecord::Base
  has_many :training_exercises
end

app/models/training_exercise.rb
class TrainingExercise < ActiveRecord::Base
  belongs_to :training
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  expose(:form) { ExerciseForm.new(exercise_params) }
  expose(:edit_form) { EditExerciseForm.new(exercise_params, exercise) }
  expose(:exercises) { Exercise.all }
  expose(:exercise) { Exercise.find(params['id']) }

  def new
    @model = NewExercisePresenter.new
  end

  def create
    if form.valid? && Exercise.create(exercise_params)
      flash[:success] = 'Ćwiczenie zostało utworzone'
      return redirect_to exercises_path
    end
    render :new
  end

  def edit
    @model = EditExercisePresenter.new(exercise)
    render :edit, locals: { form: edit_form }
  end

  def update
    if edit_form.valid? && ExerciseUpdater.new(exercise.id, edit_form).call
      flash[:success] = 'Ćwiczenie zostało zaktualizowane'
      redirect_to exercises_path
    else
      render :edit, locals: { form: edit_form }
    end
  end

  def index; end

  def destroy
    exercise.destroy
    flash[:success] = 'Ćwiczenie zostało usunięte'
    redirect_to exercises_path
  end

  private

  def exercise_params
    params.permit(:name, :description, :audio, :double_sided)
  end
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def create
    File.open(file_path, 'wb') { |f| f.write(params[:audio_file].read) }
    render nothing: true
  end

  private

  def file_path
    Rails.public_path.join(params[:audio])
  end
end

app/controllers/trainings_controller.rb
class TrainingsController < ApplicationController
  expose(:form) { TrainingForm.new(params) }
  expose(:edit_form) { EditTrainingForm.new(params, training) }
  expose(:trainings) { Training.all }
  expose(:training) { Training.find(params['id']) }
  expose(:exercises) { Exercise.all }

  def new
  end

  def create
    if form.valid? && TrainingCreator.new(form).call
      flash[:success] = 'Trening został utworzony'
      return redirect_to trainings_path
    end
    render :new
  end

  def edit
    render :edit, locals: { form: edit_form }
  end

  def update
    if edit_form.valid? && TrainingUpdater.new(form, training).call
      flash[:success] = 'Trening zaktualizowany'
      redirect_to trainings_path
    else
      render :edit
    end
  end

  def index
  end

  def destroy
    training.destroy
    flash[:success] = 'Ćwiczenie zostało usunięte'
    redirect_to trainings_path
  end

  private

  def training_params
    params.permit(:name, :exercises)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/exercises/_exercise_form.haml
= hidden_field_tag :audio, form.audio
.row.form-group
  %label.col-md-1{ for: :name }
    Nazwa:
  .col-md-5
    = text_field_tag :name, form.name, placeholder: 'Nazwa ćwiczenia', class: 'form-control'
.row.form-group
  %label.col-md-1{ for: :description }
    Opis:
  .col-md-5
    = text_area_tag :description, form.name, placeholder: 'Opis ćwiczenia', class: 'form-control', size: '30x5'
.row.form-group
  %label.col-md-1{ for: :audio }
    Nagranie:
  .col-md-5
    = file_field_tag :audio
    #audio_container
    - if @model.audio_file_exists?
      %audio{controls: ''}
        %source{src: "#{form.audio.url}", type: 'audio/ogg'}
.row.form-group
  %label.col-md-1{ for: :double_sided }
    Ćwiczenie dwustronne
  .col-md-5
    = hidden_field_tag :double_sided, false, class: 'js-double-sided-hidden-input'
    = check_box_tag :double_sided, true, form.double_sided, class: 'js-double-sided-checkbox-input'

app/views/exercises/edit.haml
.row
  %h1 Edytuj ćwiczenie
.row
  = form_tag exercise_path, method: 'PATCH', class: 'form-horizontal', id: 'exercise_form', multipart: true do
    = render 'layouts/form_errors'
    = render 'exercise_form', form: edit_form
    .row
      .col-md-6
        %button.btn.btn-default.pull-right.js-save-button
          Aktualizuj

app/views/exercises/index.haml
.row
  %h1
    Wszystkie ćwiczenia
.row
  = link_to 'Dodaj nowe ćwiczenie', new_exercise_path, class: 'btn btn-primary js-add-new-button'
  %br
  %br
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th Index:
      %th.col-md-2 Nazwa:
      %th.col-md-8 Opis:
      %th Dwustronne
      %th Akcje:
  %tbody
    - exercises.to_enum.with_index(1).each do |exercise, index|
      %tr
        %td.js-exercise-index
          = index
        %td
          = exercise.name
        %td
          = exercise.description
        %td
          = exercise.decorate.double_sided_human
        %td{ style: 'text-align: center' }
          .btn-group
            = link_to 'Edytuj', edit_exercise_path(exercise.id), class: 'btn-primary btn js-edit-button', role: 'button'
            = link_to 'Usuń', exercise_path(exercise.id), method: 'DELETE', class: 'btn-danger btn', role: 'button'

app/views/exercises/new.haml
.row
  %h1 Dodaj nowe ćwiczenie
.row
  = form_tag exercises_path, class: 'form-horizontal', id: 'exercise_form' do
    = render 'layouts/form_errors'
    = render 'exercise_form', form: form
    .row
      .col-md-6
        %button.btn.btn-default.pull-right.js-save-button
          Dodaj

app/views/layouts/_flashes.haml
.container
  - flash.each do |type, message|
    .alert.fade.in{ class: "alert-#{type}" }
      %a.close{ href: '#', 'data-dismiss' => 'alert', 'aria-label' => 'close' }
        &times;
      = message

app/views/layouts/_form_errors.haml
- if form.errors.full_messages.present?
  .row
    .col-sm-9
      .alert.alert-danger{style: 'margin-top: 10px'}
        The following errors prevented the form from being saved:
        %ul
          - form.errors.full_messages.each do |msg|
            %li= msg

app/views/layouts/application.haml
!!!
%html
  %head
    %title Trainapp
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %a.navbar-brand(href="#") TrainApp
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            %li= link_to 'Ćwiczenia', exercises_path
            %li= link_to 'Treningi', trainings_path
    .container
      .row
        .col-lg-12
          = render 'layouts/flashes'
          = yield

app/views/trainings/_form.haml
.row.form-group
  %label.col-md-1{ for: :name }
    Nazwa:
  .col-md-11
    = text_field_tag :name, form.name, placeholder: 'Nazwa', class: 'form-control js-training-name-input'
.row
  %label.col-md-1
    Ćwiczenia
  .col-md-11
    %table.table.table-striped.table-bordered.table-hover.js-training-exercises-table
      %thead
        %tr
          %th Zaznacz
          %th.col-md-2 Nazwa:
          %th.col-md-8 Opis:
          %th Ustawienia:
      %tbody
        - exercises.each_with_index do |exercise, index|
          %tr
            %td{ style: 'text-align: center' }
              = hidden_field_tag 'exercises_ids[]', exercise.id
            %td
              = exercise.name
            %td
              = exercise.description
            %td.traning-exercise-details
              .row
                .col-md-4
                  Czas:
                .col-md-6
                  = text_field_tag 'exercises_duration[]', form.exercises_duration[index], class: 'duration-input js-duration-input'
              .row
                .col-md-4
                  Serie:
                .col-md-6
                  = text_field_tag 'exercises_series_number[]', form.exercises_series_number[index], class: 'series-number-input js-series-number-input'
              .row
                .col-md-6
                  = exercise.decorate.double_sided_human

.row
  .col-md-12
    %button.btn.btn-default.pull-right.js-save-button
      Zapisz

app/views/trainings/edit.haml
.row
  %h1 Edytuj trening
.row
  = form_tag training_path, method: 'PATCH', class: 'form-horizontal', id: 'exercise_form' do
    = render 'layouts/form_errors'
    = render 'form', form: edit_form

app/views/trainings/index.haml
.row
  %h1
    Wszystkie treningi
.row
  = link_to 'Dodaj nowy', new_training_path, class: 'btn btn-primary js-add-new-button'
  %br
  %br
%table.table.table-striped.table-bordered.table-hover
  %thead
    %tr
      %th.col-md-2 Nazwa:
      %th Akcje:
  %tbody
    - trainings.each do |training|
      %tr
        %td
          = training.name
        %td{ style: 'text-align: center' }
          .btn-group
            = link_to 'Edytuj', edit_training_path(training.id), class: 'btn-primary btn', role: 'button'
            = link_to 'Usuń', training_path(training.id), method: 'DELETE', class: 'btn-danger btn', role: 'button'

app/views/trainings/new.haml
.row
  %h1 Dodaj nowy trening
.row
  = form_tag trainings_path, class: 'form-horizontal', id: 'exercise_form' do
    = render 'layouts/form_errors'
    = render 'form', form: form